name: "\U0001F680 Feature Request"
description: Share an idea
labels: ["idea"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for sharing your idea to refine the keyframe refiner.

        Please fill out the following form as detailed as possible.
  - type: textarea
    attributes:
      label: Motivation
      description: What brings you here?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: How can you solve the problem?
    validations:
      required: true
